#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/24856556-4d07-4e7a-9280-987c04a25c2b/ # 
title: Spotify API
version: v1
/artists:
  get:
    description: Get all artists
    responses:
     404:
      body:
        application/json:
